[workspace.package]
license = "MIT-0"
authors = ["Parity Technologies <admin@parity.io>"]
homepage = "https://paritytech.github.io/polkadot-sdk/"
repository = "https://github.com/paritytech/polkadot-sdk-parachain-template.git"
edition = "2021"

[workspace]
default-members = [
    "pallets/pallet-credential-governance",
    "pallets/pallet-identity-registry",
    "pallets/pallet-verifiable-credentials",
    "pallets/pallet-xcm-credentials",
    "pallets/pallet-zk-credentials",
    "runtime"
]
members = [
    "node",
    "pallets/pallet-credential-governance",
    "pallets/pallet-identity-registry",
    "pallets/pallet-verifiable-credentials",
    "pallets/pallet-xcm-credentials",
    "pallets/pallet-zk-credentials",
    "runtime",
]
resolver = "2"

[workspace.dependencies]
parachain-template-runtime = { path = "./runtime", default-features = false }
pallet-credential-governance = { path = "./pallets/pallet-credential-governance", default-features = false }
pallet-identity-registry = { path = "./pallets/pallet-identity-registry", default-features = false }
pallet-verifiable-credentials = { path = "./pallets/pallet-verifiable-credentials", default-features = false }
pallet-xcm-credentials = { path = "./pallets/pallet-xcm-credentials", default-features = false }
pallet-zk-credentials = { path = "./pallets/pallet-zk-credentials", default-features = false }
sp-core = { version = "38.1.0", default-features = false, package = "sp-core" }
sp-runtime = { version = "44.0.0", default-features = false, package = "sp-runtime" }
sp-std = { version = "14.0.0", default-features = false, package = "sp-std" }
frame-benchmarking = { default-features = false, optional = false, version = "43.0.0" }
frame-executive = { default-features = false, version = "43.0.0" }
frame-support = { default-features = false, version = "43.0.0" }
frame-system = { default-features = false, version = "43.0.0" }
frame-system-benchmarking = { default-features = false, optional = false, version = "43.0.0" }
frame-system-rpc-runtime-api = { default-features = false, version = "39.0.0" }
frame-try-runtime = { version = "0.49.0", default-features = false, optional = false }
pallet-balances = { default-features = false, version = "44.0.0" }
pallet-sudo = { version = "43.0.0", default-features = false }
pallet-timestamp = { default-features = false, version = "42.0.0" }
pallet-transaction-payment = { default-features = false, version = "43.0.0" }
pallet-transaction-payment-rpc-runtime-api = { default-features = false, version = "43.0.0" }
sp-api = { default-features = false, version = "39.0.0" }
sp-block-builder = { default-features = false, version = "39.0.0" }
sp-inherents = { default-features = false, version = "39.0.0" }
sp-offchain = { default-features = false, version = "39.0.0" }
sp-session = { default-features = false, version = "41.0.0" }
sp-transaction-pool = { default-features = false, version = "39.0.0" }
sp-version = { default-features = false, version = "42.0.0" }
sp-io = { version = "23.0.0", default-features = false }
xcm = { git = "https://github.com/paritytech/polkadot.git", tag = "v1.0.0-rc5", default-features = false }
cumulus-primitives-core = { version = "0.20.0", default-features = false }
clap = { version = "4.5.13" }
color-print = { version = "0.3.4" }
docify = { version = "0.2.9" }
futures = { version = "0.3.31" }
jsonrpsee = { version = "0.24.3" }
log = { version = "0.4.22", default-features = false }
polkadot-sdk = { version = "0.18.0", default-features = false }
prometheus-endpoint = { version = "0.17.2", default-features = false, package = "substrate-prometheus-endpoint" }
serde = { version = "1.0.214", default-features = false }
codec = { version = "3.7.4", default-features = false, package = "parity-scale-codec" }
cumulus-pallet-parachain-system = { version = "0.20.0", default-features = false }
hex-literal = { version = "0.4.1", default-features = false }
scale-info = { version = "2.11.6", default-features = false }
serde_json = { version = "1.0.132", default-features = false }
smallvec = { version = "1.11.0", default-features = false }
substrate-wasm-builder = { version = "26.0.1", default-features = false }
frame = { version = "0.9.1", default-features = false, package = "polkadot-sdk-frame" }

[profile.release]
opt-level = 3
panic = "unwind"

[profile.production]
codegen-units = 1
inherits = "release"
lto = true

[patch.crates-io]
xcm = { git = "https://github.com/paritytech/polkadot.git", tag = "v1.0.0-rc5" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot.git", tag = "v1.0.0-rc5" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech/cumulus.git", tag = "v1.0.0-rc5" }
polkadot-primitives = { git = "https://github.com/paritytech/polkadot.git", tag = "v1.0.0-rc5" }